/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author leone
 */
import Negocio.Coordinador;
import Datos.Configuracion;

import java.util.ArrayList;
import javax.swing.JTextField;
import Datos.XmlRead;
import javax.swing.JOptionPane;
import Datos.Logs;
import javax.swing.JFileChooser;
import java.io.*;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;

public class PanelAjustes extends javax.swing.JPanel {
    /**
     * Creates new form PanelAjustes
     */
    private Coordinador cor;
    private Configuracion Conf;
    private Configuracion Confread;
    private ArrayList<String> puertos;
    private ArrayList<String> Images;
    private ArrayList<String> Alias;
    private String PuertoUDP;
    private XmlRead X;
    private Panel P;
    private PanelMixer Mixer;
    private String Inteface;
    
    public PanelAjustes(Coordinador cor,Panel P,PanelMixer Mixer) {
        puertos=new ArrayList<>();
        Images=new ArrayList<>();
        Alias=new ArrayList<>();
        this.cor=cor;
        Conf=new Configuracion();
        Confread=new Configuracion();
        initComponents();
        X=new XmlRead();
               
        //pintar configuracion principal
        PaintSettings(cor.GetConfiguracion());     
        this.P=P;
        this.Mixer=Mixer;
        for(int i=0;i<32;i++){
            Images.add("0");
        }
        Confread=X.Read("config.xml");
        Alias=Confread.GetAlias();
        Images=Confread.GetListaImages();
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel156 = new javax.swing.JLabel();
        id9 = new javax.swing.JTextField();
        jLabel157 = new javax.swing.JLabel();
        id10 = new javax.swing.JTextField();
        jLabel158 = new javax.swing.JLabel();
        id11 = new javax.swing.JTextField();
        jLabel159 = new javax.swing.JLabel();
        jLabel160 = new javax.swing.JLabel();
        id12 = new javax.swing.JTextField();
        jLabel161 = new javax.swing.JLabel();
        jLabel162 = new javax.swing.JLabel();
        id15 = new javax.swing.JTextField();
        id14 = new javax.swing.JTextField();
        jLabel163 = new javax.swing.JLabel();
        id16 = new javax.swing.JTextField();
        id13 = new javax.swing.JTextField();
        jLabel164 = new javax.swing.JLabel();
        jLabel165 = new javax.swing.JLabel();
        jLabel166 = new javax.swing.JLabel();
        jLabel167 = new javax.swing.JLabel();
        jLabel168 = new javax.swing.JLabel();
        jLabel169 = new javax.swing.JLabel();
        jLabel170 = new javax.swing.JLabel();
        jLabel171 = new javax.swing.JLabel();
        jLabel172 = new javax.swing.JLabel();
        jLabel173 = new javax.swing.JLabel();
        jLabel174 = new javax.swing.JLabel();
        jLabel175 = new javax.swing.JLabel();
        jLabel176 = new javax.swing.JLabel();
        jLabel177 = new javax.swing.JLabel();
        jLabel178 = new javax.swing.JLabel();
        jLabel179 = new javax.swing.JLabel();
        jLabel213 = new javax.swing.JLabel();
        jLabel215 = new javax.swing.JLabel();
        jLabel216 = new javax.swing.JLabel();
        jLabel217 = new javax.swing.JLabel();
        ch1 = new javax.swing.JTextField();
        ch2 = new javax.swing.JTextField();
        jLabel219 = new javax.swing.JLabel();
        jLabel220 = new javax.swing.JLabel();
        Default = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        serv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        multicast = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        puerto = new javax.swing.JTextField();
        id1 = new javax.swing.JTextField();
        id2 = new javax.swing.JTextField();
        id3 = new javax.swing.JTextField();
        id4 = new javax.swing.JTextField();
        id5 = new javax.swing.JTextField();
        id6 = new javax.swing.JTextField();
        id7 = new javax.swing.JTextField();
        id8 = new javax.swing.JTextField();
        id17 = new javax.swing.JTextField();
        id18 = new javax.swing.JTextField();
        id19 = new javax.swing.JTextField();
        id20 = new javax.swing.JTextField();
        id21 = new javax.swing.JTextField();
        id22 = new javax.swing.JTextField();
        id24 = new javax.swing.JTextField();
        id23 = new javax.swing.JTextField();
        id26 = new javax.swing.JTextField();
        id25 = new javax.swing.JTextField();
        id27 = new javax.swing.JTextField();
        id29 = new javax.swing.JTextField();
        id28 = new javax.swing.JTextField();
        id30 = new javax.swing.JTextField();
        id32 = new javax.swing.JTextField();
        id31 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Frecuencys = new javax.swing.JTextField();
        Samples = new javax.swing.JTextField();
        Aceptar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        C1 = new javax.swing.JTextField();
        C2 = new javax.swing.JTextField();
        C3 = new javax.swing.JTextField();
        C9 = new javax.swing.JTextField();
        C10 = new javax.swing.JTextField();
        C11 = new javax.swing.JTextField();
        C13 = new javax.swing.JTextField();
        C12 = new javax.swing.JTextField();
        C14 = new javax.swing.JTextField();
        C15 = new javax.swing.JTextField();
        C16 = new javax.swing.JTextField();
        C17 = new javax.swing.JTextField();
        C18 = new javax.swing.JTextField();
        C19 = new javax.swing.JTextField();
        C20 = new javax.swing.JTextField();
        C21 = new javax.swing.JTextField();
        C22 = new javax.swing.JTextField();
        C23 = new javax.swing.JTextField();
        C24 = new javax.swing.JTextField();
        jLabel221 = new javax.swing.JLabel();
        C25 = new javax.swing.JTextField();
        C26 = new javax.swing.JTextField();
        C27 = new javax.swing.JTextField();
        C28 = new javax.swing.JTextField();
        C29 = new javax.swing.JTextField();
        C30 = new javax.swing.JTextField();
        C31 = new javax.swing.JTextField();
        C32 = new javax.swing.JTextField();
        C4 = new javax.swing.JTextField();
        C5 = new javax.swing.JTextField();
        C6 = new javax.swing.JTextField();
        C7 = new javax.swing.JTextField();
        C8 = new javax.swing.JTextField();
        jLabel222 = new javax.swing.JLabel();
        Im1 = new javax.swing.JButton();
        Im2 = new javax.swing.JButton();
        Im3 = new javax.swing.JButton();
        Im4 = new javax.swing.JButton();
        Im5 = new javax.swing.JButton();
        Im6 = new javax.swing.JButton();
        Im7 = new javax.swing.JButton();
        Im8 = new javax.swing.JButton();
        Im9 = new javax.swing.JButton();
        Im10 = new javax.swing.JButton();
        Im11 = new javax.swing.JButton();
        Im12 = new javax.swing.JButton();
        Im13 = new javax.swing.JButton();
        Im14 = new javax.swing.JButton();
        Im15 = new javax.swing.JButton();
        Im16 = new javax.swing.JButton();
        Im17 = new javax.swing.JButton();
        Im18 = new javax.swing.JButton();
        Im19 = new javax.swing.JButton();
        Im20 = new javax.swing.JButton();
        Im21 = new javax.swing.JButton();
        Im22 = new javax.swing.JButton();
        Im23 = new javax.swing.JButton();
        Im24 = new javax.swing.JButton();
        Im25 = new javax.swing.JButton();
        Im26 = new javax.swing.JButton();
        Im27 = new javax.swing.JButton();
        Im28 = new javax.swing.JButton();
        Im29 = new javax.swing.JButton();
        Im30 = new javax.swing.JButton();
        Im31 = new javax.swing.JButton();
        Im32 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setLayout(null);

        jLabel156.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel156.setForeground(new java.awt.Color(255, 255, 255));
        jLabel156.setText("CHANNEL 9");
        add(jLabel156);
        jLabel156.setBounds(220, 110, 59, 14);

        id9.setText("10001");
        id9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id9ActionPerformed(evt);
            }
        });
        add(id9);
        id9.setBounds(290, 110, 60, 20);

        jLabel157.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel157.setForeground(new java.awt.Color(255, 255, 255));
        jLabel157.setText("CHANNEL 10");
        add(jLabel157);
        jLabel157.setBounds(220, 180, 66, 14);

        id10.setText("10001");
        id10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id10ActionPerformed(evt);
            }
        });
        add(id10);
        id10.setBounds(290, 180, 60, 20);

        jLabel158.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel158.setForeground(new java.awt.Color(255, 255, 255));
        jLabel158.setText("CHANNEL 11");
        add(jLabel158);
        jLabel158.setBounds(1020, 110, 66, 14);

        id11.setText("10001");
        id11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id11ActionPerformed(evt);
            }
        });
        add(id11);
        id11.setBounds(1090, 110, 70, 20);

        jLabel159.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel159.setForeground(new java.awt.Color(255, 255, 255));
        jLabel159.setText("CHANNEL 13");
        add(jLabel159);
        jLabel159.setBounds(220, 250, 66, 14);

        jLabel160.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel160.setForeground(new java.awt.Color(255, 255, 255));
        jLabel160.setText("CHANNEL 12");
        add(jLabel160);
        jLabel160.setBounds(1020, 180, 66, 14);

        id12.setText("10001");
        id12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id12ActionPerformed(evt);
            }
        });
        add(id12);
        id12.setBounds(1090, 180, 70, 20);

        jLabel161.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel161.setForeground(new java.awt.Color(255, 255, 255));
        jLabel161.setText("CHANNEL 15");
        add(jLabel161);
        jLabel161.setBounds(220, 320, 66, 14);

        jLabel162.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel162.setForeground(new java.awt.Color(255, 255, 255));
        jLabel162.setText("CHANNEL 14");
        add(jLabel162);
        jLabel162.setBounds(1020, 250, 66, 14);

        id15.setText("10001");
        id15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id15ActionPerformed(evt);
            }
        });
        add(id15);
        id15.setBounds(290, 320, 60, 20);

        id14.setText("10001");
        id14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id14ActionPerformed(evt);
            }
        });
        add(id14);
        id14.setBounds(1090, 250, 70, 20);

        jLabel163.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel163.setForeground(new java.awt.Color(255, 255, 255));
        jLabel163.setText("CHANNEL 16");
        add(jLabel163);
        jLabel163.setBounds(1020, 320, 66, 14);

        id16.setText("10001");
        id16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id16ActionPerformed(evt);
            }
        });
        add(id16);
        id16.setBounds(1090, 320, 70, 20);

        id13.setText("10001");
        id13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id13ActionPerformed(evt);
            }
        });
        add(id13);
        id13.setBounds(290, 250, 60, 20);

        jLabel164.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel164.setForeground(new java.awt.Color(255, 255, 255));
        jLabel164.setText("CHANNEL 17");
        add(jLabel164);
        jLabel164.setBounds(420, 110, 66, 14);

        jLabel165.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel165.setForeground(new java.awt.Color(255, 255, 255));
        jLabel165.setText("CHANNEL 18");
        add(jLabel165);
        jLabel165.setBounds(420, 180, 66, 14);

        jLabel166.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel166.setForeground(new java.awt.Color(255, 255, 255));
        jLabel166.setText("CHANNEL 19");
        add(jLabel166);
        jLabel166.setBounds(1220, 110, 66, 14);

        jLabel167.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel167.setForeground(new java.awt.Color(255, 255, 255));
        jLabel167.setText("CHANNEL 21");
        add(jLabel167);
        jLabel167.setBounds(420, 250, 66, 14);

        jLabel168.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel168.setForeground(new java.awt.Color(255, 255, 255));
        jLabel168.setText("CHANNEL 20");
        add(jLabel168);
        jLabel168.setBounds(1220, 180, 66, 14);

        jLabel169.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel169.setForeground(new java.awt.Color(255, 255, 255));
        jLabel169.setText("CHANNEL 23");
        add(jLabel169);
        jLabel169.setBounds(420, 320, 66, 14);

        jLabel170.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel170.setForeground(new java.awt.Color(255, 255, 255));
        jLabel170.setText("CHANNEL 22");
        add(jLabel170);
        jLabel170.setBounds(1220, 250, 66, 14);

        jLabel171.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel171.setForeground(new java.awt.Color(255, 255, 255));
        jLabel171.setText("CHANNEL 24");
        add(jLabel171);
        jLabel171.setBounds(1220, 320, 66, 14);

        jLabel172.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel172.setForeground(new java.awt.Color(255, 255, 255));
        jLabel172.setText("CHANNEL 25");
        add(jLabel172);
        jLabel172.setBounds(620, 110, 66, 14);

        jLabel173.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel173.setForeground(new java.awt.Color(255, 255, 255));
        jLabel173.setText("CHANNEL 26");
        add(jLabel173);
        jLabel173.setBounds(610, 180, 66, 14);

        jLabel174.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel174.setForeground(new java.awt.Color(255, 255, 255));
        jLabel174.setText("CHANNEL 27");
        add(jLabel174);
        jLabel174.setBounds(1420, 110, 66, 14);

        jLabel175.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel175.setForeground(new java.awt.Color(255, 255, 255));
        jLabel175.setText("CHANNEL 29");
        add(jLabel175);
        jLabel175.setBounds(610, 250, 66, 14);

        jLabel176.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel176.setForeground(new java.awt.Color(255, 255, 255));
        jLabel176.setText("CHANNEL 28");
        add(jLabel176);
        jLabel176.setBounds(1420, 180, 66, 14);

        jLabel177.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel177.setForeground(new java.awt.Color(255, 255, 255));
        jLabel177.setText("CHANNEL 31");
        add(jLabel177);
        jLabel177.setBounds(620, 320, 66, 14);

        jLabel178.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel178.setForeground(new java.awt.Color(255, 255, 255));
        jLabel178.setText("CHANNEL 30");
        add(jLabel178);
        jLabel178.setBounds(1420, 250, 66, 14);

        jLabel179.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel179.setForeground(new java.awt.Color(255, 255, 255));
        jLabel179.setText("CHANNEL 32");
        add(jLabel179);
        jLabel179.setBounds(1420, 320, 66, 14);

        jLabel213.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel213.setForeground(new java.awt.Color(255, 255, 255));
        jLabel213.setText("CHANNEL 7");
        add(jLabel213);
        jLabel213.setBounds(20, 320, 59, 14);

        jLabel215.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel215.setForeground(new java.awt.Color(255, 255, 255));
        jLabel215.setText("CHANNEL 8");
        add(jLabel215);
        jLabel215.setBounds(830, 320, 59, 14);

        jLabel216.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel216.setForeground(new java.awt.Color(255, 255, 255));
        jLabel216.setText("CHANNEL 5");
        add(jLabel216);
        jLabel216.setBounds(20, 250, 59, 14);

        jLabel217.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel217.setForeground(new java.awt.Color(255, 255, 255));
        jLabel217.setText("CHANNEL 1");
        add(jLabel217);
        jLabel217.setBounds(20, 110, 59, 14);

        ch1.setText("10001");
        ch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch1ActionPerformed(evt);
            }
        });
        add(ch1);
        ch1.setBounds(140, 50, 78, 20);

        ch2.setText("10001");
        ch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch2ActionPerformed(evt);
            }
        });
        add(ch2);
        ch2.setBounds(280, 50, 78, 20);

        jLabel219.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel219.setForeground(new java.awt.Color(255, 255, 255));
        jLabel219.setText("CHANNEL 3");
        add(jLabel219);
        jLabel219.setBounds(830, 110, 59, 14);

        jLabel220.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel220.setForeground(new java.awt.Color(255, 255, 255));
        jLabel220.setText("CHANNEL 4");
        add(jLabel220);
        jLabel220.setBounds(830, 180, 59, 14);

        Default.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Default.setText("Default");
        Default.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefaultActionPerformed(evt);
            }
        });
        add(Default);
        Default.setBounds(850, 460, 119, 36);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SERVIDOR");
        add(jLabel1);
        jLabel1.setBounds(22, 11, 61, 22);

        serv.setText("127.0.0.1");
        serv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servActionPerformed(evt);
            }
        });
        add(serv);
        serv.setBounds(140, 10, 78, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MULTICAST");
        add(jLabel2);
        jLabel2.setBounds(281, 11, 84, 22);

        multicast.setText("230.0.0.1");
        multicast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multicastActionPerformed(evt);
            }
        });
        add(multicast);
        multicast.setBounds(428, 12, 68, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PUERTO TCP");
        add(jLabel3);
        jLabel3.setBounds(548, 11, 86, 22);

        puerto.setText("10000");
        puerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puertoActionPerformed(evt);
            }
        });
        add(puerto);
        puerto.setBounds(644, 12, 59, 20);

        id1.setText("alguien");
        id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id1ActionPerformed(evt);
            }
        });
        add(id1);
        id1.setBounds(90, 110, 70, 20);

        id2.setText("alguien");
        id2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id2ActionPerformed(evt);
            }
        });
        add(id2);
        id2.setBounds(90, 180, 70, 20);

        id3.setText("alguien");
        id3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id3ActionPerformed(evt);
            }
        });
        add(id3);
        id3.setBounds(890, 110, 70, 20);

        id4.setText("alguien");
        id4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id4ActionPerformed(evt);
            }
        });
        add(id4);
        id4.setBounds(890, 180, 70, 20);

        id5.setText("alguien");
        id5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id5ActionPerformed(evt);
            }
        });
        add(id5);
        id5.setBounds(90, 250, 70, 20);

        id6.setText("10001");
        id6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id6ActionPerformed(evt);
            }
        });
        add(id6);
        id6.setBounds(890, 250, 70, 20);

        id7.setText("alguien");
        id7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id7ActionPerformed(evt);
            }
        });
        add(id7);
        id7.setBounds(90, 320, 70, 20);

        id8.setText("10001");
        id8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id8ActionPerformed(evt);
            }
        });
        add(id8);
        id8.setBounds(890, 320, 70, 20);

        id17.setText("10001");
        id17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id17ActionPerformed(evt);
            }
        });
        add(id17);
        id17.setBounds(490, 110, 70, 20);

        id18.setText("10001");
        id18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id18ActionPerformed(evt);
            }
        });
        add(id18);
        id18.setBounds(490, 180, 70, 20);

        id19.setText("10001");
        id19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id19ActionPerformed(evt);
            }
        });
        add(id19);
        id19.setBounds(1290, 110, 70, 20);

        id20.setText("10001");
        id20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id20ActionPerformed(evt);
            }
        });
        add(id20);
        id20.setBounds(1290, 180, 70, 20);

        id21.setText("10001");
        id21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id21ActionPerformed(evt);
            }
        });
        add(id21);
        id21.setBounds(490, 250, 70, 20);

        id22.setText("10001");
        id22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id22ActionPerformed(evt);
            }
        });
        add(id22);
        id22.setBounds(1290, 250, 70, 20);

        id24.setText("10001");
        id24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id24ActionPerformed(evt);
            }
        });
        add(id24);
        id24.setBounds(1290, 320, 70, 20);

        id23.setText("10001");
        id23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id23ActionPerformed(evt);
            }
        });
        add(id23);
        id23.setBounds(490, 320, 70, 20);

        id26.setText("10001");
        id26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id26ActionPerformed(evt);
            }
        });
        add(id26);
        id26.setBounds(690, 180, 77, 20);

        id25.setText("10001");
        id25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id25ActionPerformed(evt);
            }
        });
        add(id25);
        id25.setBounds(690, 110, 77, 20);

        id27.setText("10001");
        id27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id27ActionPerformed(evt);
            }
        });
        add(id27);
        id27.setBounds(1490, 110, 60, 20);

        id29.setText("10001");
        id29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id29ActionPerformed(evt);
            }
        });
        add(id29);
        id29.setBounds(690, 250, 77, 20);

        id28.setText("10001");
        id28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id28ActionPerformed(evt);
            }
        });
        add(id28);
        id28.setBounds(1490, 180, 60, 20);

        id30.setText("10001");
        id30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id30ActionPerformed(evt);
            }
        });
        add(id30);
        id30.setBounds(1490, 250, 60, 20);

        id32.setText("10001");
        id32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id32ActionPerformed(evt);
            }
        });
        add(id32);
        id32.setBounds(1490, 320, 60, 20);

        id31.setText("10001");
        id31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id31ActionPerformed(evt);
            }
        });
        add(id31);
        id31.setBounds(690, 320, 77, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FRECUENCIA");
        add(jLabel4);
        jLabel4.setBounds(820, 11, 90, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MUESTRA");
        add(jLabel5);
        jLabel5.setBounds(1016, 11, 54, 22);

        Frecuencys.setText("48000");
        Frecuencys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrecuencysActionPerformed(evt);
            }
        });
        add(Frecuencys);
        Frecuencys.setBounds(914, 12, 59, 20);

        Samples.setText("128");
        Samples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SamplesActionPerformed(evt);
            }
        });
        add(Samples);
        Samples.setBounds(1088, 12, 59, 20);

        Aceptar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Aceptar.setText("Accept");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        add(Aceptar);
        Aceptar.setBounds(640, 460, 119, 38);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PUERTO UDP");
        add(jLabel6);
        jLabel6.setBounds(20, 50, 70, 14);

        C1.setText("1");
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });
        add(C1);
        C1.setBounds(170, 110, 30, 20);

        C2.setText("2");
        add(C2);
        C2.setBounds(170, 180, 30, 20);

        C3.setText("3");
        add(C3);
        C3.setBounds(970, 110, 30, 20);

        C9.setText("9");
        C9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C9ActionPerformed(evt);
            }
        });
        add(C9);
        C9.setBounds(360, 110, 30, 20);

        C10.setText("10");
        add(C10);
        C10.setBounds(360, 180, 30, 20);

        C11.setText("jTextField1");
        add(C11);
        C11.setBounds(1170, 110, 30, 20);

        C13.setText("jTextField1");
        add(C13);
        C13.setBounds(360, 250, 30, 20);

        C12.setText("jTextField1");
        add(C12);
        C12.setBounds(1170, 180, 30, 20);

        C14.setText("jTextField1");
        add(C14);
        C14.setBounds(1170, 250, 30, 20);

        C15.setText("jTextField1");
        add(C15);
        C15.setBounds(360, 320, 30, 20);

        C16.setText("jTextField1");
        add(C16);
        C16.setBounds(1170, 320, 30, 20);

        C17.setText("jTextField1");
        C17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C17ActionPerformed(evt);
            }
        });
        add(C17);
        C17.setBounds(570, 110, 30, 20);

        C18.setText("jTextField1");
        add(C18);
        C18.setBounds(570, 180, 30, 20);

        C19.setText("jTextField1");
        add(C19);
        C19.setBounds(1370, 110, 30, 20);

        C20.setText("jTextField1");
        add(C20);
        C20.setBounds(1370, 180, 30, 20);

        C21.setText("jTextField1");
        add(C21);
        C21.setBounds(570, 250, 30, 20);

        C22.setText("jTextField1");
        add(C22);
        C22.setBounds(1370, 250, 30, 20);

        C23.setText("jTextField1");
        add(C23);
        C23.setBounds(570, 320, 30, 20);

        C24.setText("jTextField1");
        add(C24);
        C24.setBounds(1370, 320, 30, 20);

        jLabel221.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel221.setForeground(new java.awt.Color(255, 255, 255));
        jLabel221.setText("CHANNEL 6");
        add(jLabel221);
        jLabel221.setBounds(830, 250, 59, 14);

        C25.setText("jTextField1");
        add(C25);
        C25.setBounds(770, 110, 30, 20);

        C26.setText("jTextField1");
        add(C26);
        C26.setBounds(770, 180, 30, 20);

        C27.setText("jTextField1");
        add(C27);
        C27.setBounds(1560, 110, 30, 20);

        C28.setText("jTextField1");
        add(C28);
        C28.setBounds(1560, 180, 30, 20);

        C29.setText("jTextField1");
        add(C29);
        C29.setBounds(770, 250, 30, 20);

        C30.setText("jTextField1");
        add(C30);
        C30.setBounds(1560, 250, 30, 20);

        C31.setText("jTextField1");
        add(C31);
        C31.setBounds(770, 320, 30, 20);

        C32.setText("jTextField1");
        add(C32);
        C32.setBounds(1560, 320, 30, 20);

        C4.setText("3");
        add(C4);
        C4.setBounds(970, 180, 30, 20);

        C5.setText("3");
        add(C5);
        C5.setBounds(170, 250, 30, 20);

        C6.setText("3");
        add(C6);
        C6.setBounds(970, 250, 30, 20);

        C7.setText("3");
        add(C7);
        C7.setBounds(170, 320, 30, 20);

        C8.setText("3");
        add(C8);
        C8.setBounds(970, 320, 30, 20);

        jLabel222.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel222.setForeground(new java.awt.Color(255, 255, 255));
        jLabel222.setText("CHANNEL 2");
        add(jLabel222);
        jLabel222.setBounds(20, 180, 59, 14);

        Im1.setText("Chose Image");
        Im1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im1ActionPerformed(evt);
            }
        });
        add(Im1);
        Im1.setBounds(20, 140, 139, 23);

        Im2.setText("Chose Image");
        Im2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im2ActionPerformed(evt);
            }
        });
        add(Im2);
        Im2.setBounds(20, 210, 139, 20);

        Im3.setText("Chose Image");
        Im3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im3ActionPerformed(evt);
            }
        });
        add(Im3);
        Im3.setBounds(830, 140, 139, 23);

        Im4.setText("Chose Image");
        Im4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im4ActionPerformed(evt);
            }
        });
        add(Im4);
        Im4.setBounds(830, 210, 139, 23);

        Im5.setText("Chose Image");
        Im5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im5ActionPerformed(evt);
            }
        });
        add(Im5);
        Im5.setBounds(20, 280, 139, 23);

        Im6.setText("Chose Image");
        Im6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im6ActionPerformed(evt);
            }
        });
        add(Im6);
        Im6.setBounds(830, 280, 139, 23);

        Im7.setText("Chose Image");
        Im7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im7ActionPerformed(evt);
            }
        });
        add(Im7);
        Im7.setBounds(20, 350, 139, 23);

        Im8.setText("Chose Image");
        Im8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im8ActionPerformed(evt);
            }
        });
        add(Im8);
        Im8.setBounds(830, 350, 139, 23);

        Im9.setText("Chose Image");
        Im9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im9ActionPerformed(evt);
            }
        });
        add(Im9);
        Im9.setBounds(220, 140, 139, 23);

        Im10.setText("Chose Image");
        Im10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im10ActionPerformed(evt);
            }
        });
        add(Im10);
        Im10.setBounds(220, 210, 139, 23);

        Im11.setText("Chose Image");
        Im11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im11ActionPerformed(evt);
            }
        });
        add(Im11);
        Im11.setBounds(1020, 140, 139, 23);

        Im12.setText("Chose Image");
        Im12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im12ActionPerformed(evt);
            }
        });
        add(Im12);
        Im12.setBounds(1020, 210, 139, 23);

        Im13.setText("Chose Image");
        Im13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im13ActionPerformed(evt);
            }
        });
        add(Im13);
        Im13.setBounds(220, 280, 139, 23);

        Im14.setText("Chose Image");
        Im14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im14ActionPerformed(evt);
            }
        });
        add(Im14);
        Im14.setBounds(1020, 280, 139, 23);

        Im15.setText("Chose Image");
        Im15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im15ActionPerformed(evt);
            }
        });
        add(Im15);
        Im15.setBounds(220, 350, 139, 23);

        Im16.setText("Chose Image");
        Im16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im16ActionPerformed(evt);
            }
        });
        add(Im16);
        Im16.setBounds(1020, 350, 139, 23);

        Im17.setText("Chose Image");
        Im17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im17ActionPerformed(evt);
            }
        });
        add(Im17);
        Im17.setBounds(420, 140, 139, 23);

        Im18.setText("Chose Image");
        Im18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im18ActionPerformed(evt);
            }
        });
        add(Im18);
        Im18.setBounds(420, 210, 139, 23);

        Im19.setText("Chose Image");
        Im19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im19ActionPerformed(evt);
            }
        });
        add(Im19);
        Im19.setBounds(1220, 140, 139, 23);

        Im20.setText("Chose Image");
        Im20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im20ActionPerformed(evt);
            }
        });
        add(Im20);
        Im20.setBounds(1220, 210, 139, 23);

        Im21.setText("Chose Image");
        Im21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im21ActionPerformed(evt);
            }
        });
        add(Im21);
        Im21.setBounds(420, 280, 139, 23);

        Im22.setText("Chose Image");
        Im22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im22ActionPerformed(evt);
            }
        });
        add(Im22);
        Im22.setBounds(1220, 280, 139, 23);

        Im23.setText("Chose Image");
        Im23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im23ActionPerformed(evt);
            }
        });
        add(Im23);
        Im23.setBounds(420, 350, 139, 23);

        Im24.setText("Chose Image");
        Im24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im24ActionPerformed(evt);
            }
        });
        add(Im24);
        Im24.setBounds(1220, 350, 139, 23);

        Im25.setText("Chose Image");
        Im25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im25ActionPerformed(evt);
            }
        });
        add(Im25);
        Im25.setBounds(620, 140, 139, 23);

        Im26.setText("Chose Image");
        Im26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im26ActionPerformed(evt);
            }
        });
        add(Im26);
        Im26.setBounds(620, 210, 139, 23);

        Im27.setText("Chose Image");
        Im27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im27ActionPerformed(evt);
            }
        });
        add(Im27);
        Im27.setBounds(1420, 140, 139, 23);

        Im28.setText("Chose Image");
        Im28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im28ActionPerformed(evt);
            }
        });
        add(Im28);
        Im28.setBounds(1420, 210, 139, 23);

        Im29.setText("Chose Image");
        Im29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im29ActionPerformed(evt);
            }
        });
        add(Im29);
        Im29.setBounds(620, 280, 139, 23);

        Im30.setText("Chose Image");
        Im30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im30ActionPerformed(evt);
            }
        });
        add(Im30);
        Im30.setBounds(1420, 280, 139, 23);

        Im31.setText("Chose Image");
        Im31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im31ActionPerformed(evt);
            }
        });
        add(Im31);
        Im31.setBounds(620, 350, 139, 23);

        Im32.setText("Chose Image");
        Im32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im32ActionPerformed(evt);
            }
        });
        add(Im32);
        Im32.setBounds(1420, 350, 139, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void id9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id9ActionPerformed

    private void id10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id10ActionPerformed

    private void id11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id11ActionPerformed

    private void id12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id12ActionPerformed

    private void id15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id15ActionPerformed

    private void id14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id14ActionPerformed

    private void id16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id16ActionPerformed

    private void id13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id13ActionPerformed

    private void ch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch1ActionPerformed

    private void ch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch2ActionPerformed

    private void servActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_servActionPerformed

    private void multicastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multicastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multicastActionPerformed

    private void puertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puertoActionPerformed

    private void id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id1ActionPerformed

    private void id2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id2ActionPerformed

    private void id3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id3ActionPerformed

    private void id4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id4ActionPerformed

    private void id5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id5ActionPerformed

    private void id6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id6ActionPerformed

    private void id7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id7ActionPerformed

    private void id8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id8ActionPerformed

    private void id17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id17ActionPerformed

    private void id18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id18ActionPerformed

    private void id19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id19ActionPerformed

    private void id20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id20ActionPerformed

    private void id21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id21ActionPerformed

    private void id22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id22ActionPerformed

    private void id24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id24ActionPerformed

    private void id23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id23ActionPerformed

    private void id26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id26ActionPerformed

    private void id25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id25ActionPerformed

    private void id27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id27ActionPerformed

    private void id29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id29ActionPerformed

    private void id28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id28ActionPerformed

    private void id30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id30ActionPerformed

    private void id32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id32ActionPerformed

    private void id31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id31ActionPerformed

    private void DefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefaultActionPerformed
        // TODO add your handling code here:
        //leer xml default
        //escribir xml
      
      
      cor.DefaultXml();
      //pintar todos los modulos a la configuracion default
      X=new XmlRead();
      Conf=X.Read("config.xml");
      this.ch1.setText(Conf.GetPortUDP());
      this.ch2.setText(Conf.GetLista().get(1));
      
      this.id9.setText(Conf.GetLista().get(8));
      this.id10.setText(Conf.GetLista().get(9));
      this.id11.setText(Conf.GetLista().get(10));
      this.id12.setText(Conf.GetLista().get(11));
      this.id13.setText(Conf.GetLista().get(12));
      this.id14.setText(Conf.GetLista().get(13));
      this.id15.setText(Conf.GetLista().get(14));
      this.id16.setText(Conf.GetLista().get(15));
      
      
      this.id1.setText(Conf.GetAlias().get(0));
      this.id2.setText(Conf.GetAlias().get(1));
      this.id3.setText(Conf.GetAlias().get(2));
      this.id4.setText(Conf.GetAlias().get(3));
      this.id5.setText(Conf.GetAlias().get(4));
      this.id6.setText(Conf.GetAlias().get(5));
      this.id7.setText(Conf.GetAlias().get(6));
      this.id8.setText(Conf.GetAlias().get(7));
      this.id9.setText(Conf.GetAlias().get(8));
      this.id10.setText(Conf.GetAlias().get(9));
      this.id11.setText(Conf.GetAlias().get(10));
      this.id12.setText(Conf.GetAlias().get(11));
      this.id13.setText(Conf.GetAlias().get(12));
      this.id14.setText(Conf.GetAlias().get(13));
      this.id15.setText(Conf.GetAlias().get(14));
      this.id16.setText(Conf.GetAlias().get(15));
      this.id17.setText(Conf.GetAlias().get(16));
      this.id18.setText(Conf.GetAlias().get(17));
      this.id19.setText(Conf.GetAlias().get(18));
      this.id20.setText(Conf.GetAlias().get(19));
      this.id21.setText(Conf.GetAlias().get(20));
      this.id22.setText(Conf.GetAlias().get(21));
      this.id23.setText(Conf.GetAlias().get(22));
      this.id24.setText(Conf.GetAlias().get(23));
      this.id25.setText(Conf.GetAlias().get(24));
      this.id26.setText(Conf.GetAlias().get(25));
      this.id27.setText(Conf.GetAlias().get(26));
      this.id28.setText(Conf.GetAlias().get(27));
      this.id29.setText(Conf.GetAlias().get(28));
      this.id30.setText(Conf.GetAlias().get(29));
      this.id31.setText(Conf.GetAlias().get(30));
      this.id32.setText(Conf.GetAlias().get(31));
      
      this.serv.setText(Conf.GetServidor());
      this.multicast.setText(Conf.GetMultiCast());
      this.puerto.setText(Conf.GetPuerto());
   
    }//GEN-LAST:event_DefaultActionPerformed

    private void FrecuencysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrecuencysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FrecuencysActionPerformed

    private void SamplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SamplesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SamplesActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        if(!puertos.isEmpty()){
            puertos.clear();
        }
        if(!Alias.isEmpty()){
            Alias.clear();
        }
             
        //Images.clear();
        Conf.SetMultiCast(multicast.getText());
        String a=multicast.getText();
        if(a.equals("") || a.equals(null)){
            JOptionPane.showMessageDialog(null, "No se ha llenado un campo");
            return;
        }

        Conf.SetPuerto(puerto.getText());
        a=puerto.getText();
        if(a.equals("") || a.equals(null)){
            JOptionPane.showMessageDialog(null, "No se ha llenado un campo");
            return;
        }

        Conf.SetServidor(serv.getText());
        a=serv.getText();
        if(a.equals("") || a.equals(null)){
            JOptionPane.showMessageDialog(null, "No se ha llenado un campo");
            return;
        }

        if(Frecuencys.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No se ha llenado un campo");
            return;
        }
        
        if(Samples.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No se ha llenado un campo");
            return;
        }

        boolean bandera1=false;
        if(Frecuencys.getText().equals("44100") || Frecuencys.getText().equals("48000")){
            bandera1=true;
        }

        boolean bandera2=false;
        if(Samples.getText().equals("128") || Samples.getText().equals("256") || Samples.getText().equals("512") || Samples.getText().equals("64")){
            bandera2=true;
        }

        if(!bandera1){
            JOptionPane.showMessageDialog(null, "la frecuencia de muestreo no es la correcta");
            return;
        }

        if(!bandera2){
            JOptionPane.showMessageDialog(null, "El tamaño de muestra no es el correcto");
            return;
        }

        Conf.SetFrecuencia(Integer.parseInt(Frecuencys.getText()) );

        Conf.SetMuestra(Integer.parseInt(Samples.getText()));

        //crear lista de todos lo canales

        if(ch1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No se ha especificado un puerto");
            return;
        }

        if(ch2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No se ha especificado un puerto");
            return;
        }
        Inteface=P.GetNetwork();

        if(Inteface==null){
            Conf.SetNet("default");
        }
        else{
            Conf.SetNet(Inteface);
        }
        
        Conf.SetPortUDP(ch1.getText());
        
        puertos.add(C1.getText());
        puertos.add(C2.getText());     
        puertos.add(C3.getText());
        puertos.add(C4.getText());
        puertos.add(C5.getText());
        puertos.add(C6.getText());
        puertos.add(C7.getText());
        puertos.add(C8.getText());
        puertos.add(C9.getText());
        puertos.add(C10.getText());
        puertos.add(C11.getText());
        puertos.add(C12.getText());
        puertos.add(C13.getText());
        puertos.add(C14.getText());
        puertos.add(C15.getText());
        puertos.add(C16.getText());
        puertos.add(C17.getText());
        puertos.add(C18.getText());
        puertos.add(C19.getText());
        puertos.add(C20.getText());
        puertos.add(C21.getText());
        puertos.add(C22.getText());
        puertos.add(C23.getText());
        puertos.add(C24.getText());
        puertos.add(C25.getText());
        puertos.add(C26.getText());
        puertos.add(C27.getText());
        puertos.add(C28.getText());
        puertos.add(C29.getText());
        puertos.add(C30.getText());
        puertos.add(C31.getText());
        puertos.add(C32.getText());
        

        //crear lista de alias
        Alias.add(id1.getText());
        Alias.add(id2.getText());
        Alias.add(id3.getText());
        Alias.add(id4.getText());
        Alias.add(id5.getText());
        Alias.add(id6.getText());
        Alias.add(id7.getText());
        Alias.add(id8.getText());
        Alias.add(id9.getText());
        Alias.add(id10.getText());
        Alias.add(id11.getText());
        Alias.add(id12.getText());
        Alias.add(id13.getText());
        Alias.add(id14.getText());
        Alias.add(id15.getText());
        Alias.add(id16.getText());
        Alias.add(id17.getText());
        Alias.add(id18.getText());
        Alias.add(id19.getText());
        Alias.add(id20.getText());
        Alias.add(id21.getText());
        Alias.add(id22.getText());
        Alias.add(id23.getText());
        Alias.add(id24.getText());
        Alias.add(id25.getText());
        Alias.add(id26.getText());
        Alias.add(id27.getText());
        Alias.add(id28.getText());
        Alias.add(id29.getText());
        Alias.add(id30.getText());
        Alias.add(id31.getText());
        Alias.add(id32.getText());

        Conf.SetLista(puertos);
        Conf.SetAlias(Alias);
        
        //lista de images (directorios)
        Conf.SetListaImages(Images);
        
        try{
            cor.WriteXml(Conf,"config.xml");
            //cor.WriteXml(Conf,"conf");
            
            JOptionPane.showMessageDialog(null, "Configuracion guardada exitosamente");
            Mixer.SetAlias(Alias);
            Mixer.SetImages(Images);
            
        }
        catch(Exception e){
            System.out.println("Error en escritura de archivo de configuracion ");
            JOptionPane.showMessageDialog(null, "Error de configuracion");
            Logs.Write("Error en escritura de archivo de configuracion");
        }
        
    }//GEN-LAST:event_AceptarActionPerformed

    private void Im1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im1ActionPerformed
        // TODO add your handling code here:
        try{
            final JFileChooser fc=new JFileChooser();
            if(fc.showOpenDialog(null)==JFileChooser.APPROVE_OPTION){
               String path=fc.getSelectedFile().getAbsolutePath();
               String nombre=fc.getSelectedFile().getName();
               
             
               
               File inFile = new File(path);
               File outFile = new File(nombre);
               FileInputStream in = new FileInputStream(inFile);
               FileOutputStream out = new FileOutputStream(outFile);
               int c;
                while( (c = in.read() ) != -1)
                    out.write(c);
                in.close();
                out.close();
                Images.remove(0);
                Images.add(0,nombre);
                
            }
            else
            {
               Images.add(null);
            }            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error de archivo ");
        }
    }//GEN-LAST:event_Im1ActionPerformed

    private void Im2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im2ActionPerformed
        // TODO add your handling code here:
        SaveImage(8);
    }//GEN-LAST:event_Im2ActionPerformed

    private void Im3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im3ActionPerformed
        // TODO add your handling code here:
         SaveImage(4);
    }//GEN-LAST:event_Im3ActionPerformed

    private void Im4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im4ActionPerformed
        // TODO add your handling code here:
         SaveImage(12);
    }//GEN-LAST:event_Im4ActionPerformed

    private void Im5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im5ActionPerformed
        // TODO add your handling code here:
         SaveImage(16);
    }//GEN-LAST:event_Im5ActionPerformed

    private void Im6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im6ActionPerformed
        // TODO add your handling code here:
         SaveImage(20);
    }//GEN-LAST:event_Im6ActionPerformed

    private void Im7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im7ActionPerformed
        // TODO add your handling code here:
         SaveImage(24);
    }//GEN-LAST:event_Im7ActionPerformed

    private void Im8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im8ActionPerformed
        // TODO add your handling code here:
         SaveImage(28);
    }//GEN-LAST:event_Im8ActionPerformed

    private void Im9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im9ActionPerformed
        // TODO add your handling code here:
        SaveImage(1);
    }//GEN-LAST:event_Im9ActionPerformed

    private void Im10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im10ActionPerformed
        // TODO add your handling code here:
        SaveImage(9);
    }//GEN-LAST:event_Im10ActionPerformed

    private void Im11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im11ActionPerformed
        // TODO add your handling code here:
        SaveImage(5);
    }//GEN-LAST:event_Im11ActionPerformed

    private void Im12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im12ActionPerformed
        // TODO add your handling code here:
        SaveImage(13);
    }//GEN-LAST:event_Im12ActionPerformed

    private void Im13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im13ActionPerformed
        // TODO add your handling code here:
        SaveImage(17);
    }//GEN-LAST:event_Im13ActionPerformed

    private void Im14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im14ActionPerformed
        // TODO add your handling code here:
        SaveImage(21);
    }//GEN-LAST:event_Im14ActionPerformed

    private void Im15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im15ActionPerformed
        // TODO add your handling code here:
        SaveImage(25);
    }//GEN-LAST:event_Im15ActionPerformed

    private void Im16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im16ActionPerformed
        // TODO add your handling code here:
        SaveImage(29);
    }//GEN-LAST:event_Im16ActionPerformed

    private void Im17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im17ActionPerformed
        // TODO add your handling code here:
        SaveImage(2);
    }//GEN-LAST:event_Im17ActionPerformed

    private void Im18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im18ActionPerformed
        // TODO add your handling code here:
        SaveImage(10);
    }//GEN-LAST:event_Im18ActionPerformed

    private void Im19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im19ActionPerformed
        // TODO add your handling code here:
        SaveImage(6);
    }//GEN-LAST:event_Im19ActionPerformed

    private void Im20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im20ActionPerformed
        // TODO add your handling code here:
        SaveImage(14);
    }//GEN-LAST:event_Im20ActionPerformed

    private void Im21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im21ActionPerformed
        // TODO add your handling code here:
        SaveImage(18);
    }//GEN-LAST:event_Im21ActionPerformed

    private void Im22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im22ActionPerformed
        // TODO add your handling code here:
        SaveImage(22);
    }//GEN-LAST:event_Im22ActionPerformed

    private void Im23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im23ActionPerformed
        // TODO add your handling code here:
        SaveImage(26);
    }//GEN-LAST:event_Im23ActionPerformed

    private void Im24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im24ActionPerformed
        // TODO add your handling code here:
        SaveImage(30);
    }//GEN-LAST:event_Im24ActionPerformed

    private void Im25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im25ActionPerformed
        // TODO add your handling code here:
        SaveImage(3);
    }//GEN-LAST:event_Im25ActionPerformed

    private void Im26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im26ActionPerformed
        // TODO add your handling code here:
        SaveImage(11);
    }//GEN-LAST:event_Im26ActionPerformed

    private void Im27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im27ActionPerformed
        // TODO add your handling code here:
        SaveImage(7);
    }//GEN-LAST:event_Im27ActionPerformed

    private void Im28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im28ActionPerformed
        // TODO add your handling code here:
        SaveImage(15);
    }//GEN-LAST:event_Im28ActionPerformed

    private void Im29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im29ActionPerformed
        // TODO add your handling code here:
        SaveImage(19);
    }//GEN-LAST:event_Im29ActionPerformed

    private void Im30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im30ActionPerformed
        // TODO add your handling code here:
        SaveImage(23);
    }//GEN-LAST:event_Im30ActionPerformed

    private void Im31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im31ActionPerformed
        // TODO add your handling code here:
        SaveImage(27);
    }//GEN-LAST:event_Im31ActionPerformed

    private void Im32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im32ActionPerformed
        // TODO add your handling code here:
        SaveImage(31);
    }//GEN-LAST:event_Im32ActionPerformed

    private void C9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C9ActionPerformed

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C1ActionPerformed

    private void C17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C17ActionPerformed

    private void PaintSettings(Configuracion C){
        
        ArrayList<String> puertos2=C.GetLista();
        ArrayList<String> nombres=C.GetAlias();
        multicast.setText(C.GetMultiCast());
        serv.setText(C.GetServidor());
        puerto.setText(C.GetPuerto());
        Samples.setText(Integer.toString(C.GetMuestra()));
        
        ch1.setText(C.GetPortUDP());
        ch2.setText(puertos2.get(1));
        
        id1.setText(nombres.get(0));
        id2.setText(nombres.get(1));
        id3.setText(nombres.get(2));
        id4.setText(nombres.get(3));
        id5.setText(nombres.get(4));
        id6.setText(nombres.get(5));
        id7.setText(nombres.get(6));
        id8.setText(nombres.get(7));
        id9.setText(nombres.get(8));
        id10.setText(nombres.get(9));
        id11.setText(nombres.get(10));
        id12.setText(nombres.get(11));
        id13.setText(nombres.get(12));
        id14.setText(nombres.get(13));
        id15.setText(nombres.get(14));
        id16.setText(nombres.get(15));
        id17.setText(nombres.get(16));
        id18.setText(nombres.get(17));
        id19.setText(nombres.get(18));
        id20.setText(nombres.get(19));
        id21.setText(nombres.get(20));
        id22.setText(nombres.get(21));
        id23.setText(nombres.get(22));
        id24.setText(nombres.get(23));
        id25.setText(nombres.get(24));
        id26.setText(nombres.get(25));
        id27.setText(nombres.get(26));
        id28.setText(nombres.get(27));
        id29.setText(nombres.get(28));
        id30.setText(nombres.get(29));
        id31.setText(nombres.get(30));
        id32.setText(nombres.get(31));
        
        C1.setText(puertos2.get(0));
        C2.setText(puertos2.get(1));
        C3.setText(puertos2.get(2));
        C4.setText(puertos2.get(3));
        C5.setText(puertos2.get(4));
        C6.setText(puertos2.get(5));
        C7.setText(puertos2.get(6));
        C8.setText(puertos2.get(7));
        C9.setText(puertos2.get(8));
        C10.setText(puertos2.get(9));
        C11.setText(puertos2.get(10));
        C12.setText(puertos2.get(11));
        C13.setText(puertos2.get(12));
        C14.setText(puertos2.get(13));
        C15.setText(puertos2.get(14));
        C16.setText(puertos2.get(15));
        C17.setText(puertos2.get(16));
        C18.setText(puertos2.get(17));
        C19.setText(puertos2.get(18));
        C20.setText(puertos2.get(19));
        C21.setText(puertos2.get(20));
        C22.setText(puertos2.get(21));
        C23.setText(puertos2.get(22));
        C24.setText(puertos2.get(23));
        C25.setText(puertos2.get(24));
        C26.setText(puertos2.get(25));
        C27.setText(puertos2.get(26));
        C28.setText(puertos2.get(27));
        C29.setText(puertos2.get(28));
        C30.setText(puertos2.get(29));
        C31.setText(puertos2.get(30));
        C32.setText(puertos2.get(31));
    }
    
    private void SaveImage(int index){
        try{
            final JFileChooser fc=new JFileChooser();
            if(fc.showOpenDialog(null)==JFileChooser.APPROVE_OPTION){
               String path=fc.getSelectedFile().getAbsolutePath();
               String nombre=fc.getSelectedFile().getName();
               File inFile = new File(path);
               File outFile = new File(nombre);
               FileInputStream in = new FileInputStream(inFile);
               FileOutputStream out = new FileOutputStream(outFile);
               int c;
                while( (c = in.read() ) != -1)
                    out.write(c);
                in.close();
                out.close();
                Images.remove(index);
                Images.add(index,nombre);
                
            }
            else
            {
               Images.add(null);
            }            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error de archivo ");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JTextField C1;
    private javax.swing.JTextField C10;
    private javax.swing.JTextField C11;
    private javax.swing.JTextField C12;
    private javax.swing.JTextField C13;
    private javax.swing.JTextField C14;
    private javax.swing.JTextField C15;
    private javax.swing.JTextField C16;
    private javax.swing.JTextField C17;
    private javax.swing.JTextField C18;
    private javax.swing.JTextField C19;
    private javax.swing.JTextField C2;
    private javax.swing.JTextField C20;
    private javax.swing.JTextField C21;
    private javax.swing.JTextField C22;
    private javax.swing.JTextField C23;
    private javax.swing.JTextField C24;
    private javax.swing.JTextField C25;
    private javax.swing.JTextField C26;
    private javax.swing.JTextField C27;
    private javax.swing.JTextField C28;
    private javax.swing.JTextField C29;
    private javax.swing.JTextField C3;
    private javax.swing.JTextField C30;
    private javax.swing.JTextField C31;
    private javax.swing.JTextField C32;
    private javax.swing.JTextField C4;
    private javax.swing.JTextField C5;
    private javax.swing.JTextField C6;
    private javax.swing.JTextField C7;
    private javax.swing.JTextField C8;
    private javax.swing.JTextField C9;
    private javax.swing.JButton Default;
    private javax.swing.JTextField Frecuencys;
    private javax.swing.JButton Im1;
    private javax.swing.JButton Im10;
    private javax.swing.JButton Im11;
    private javax.swing.JButton Im12;
    private javax.swing.JButton Im13;
    private javax.swing.JButton Im14;
    private javax.swing.JButton Im15;
    private javax.swing.JButton Im16;
    private javax.swing.JButton Im17;
    private javax.swing.JButton Im18;
    private javax.swing.JButton Im19;
    private javax.swing.JButton Im2;
    private javax.swing.JButton Im20;
    private javax.swing.JButton Im21;
    private javax.swing.JButton Im22;
    private javax.swing.JButton Im23;
    private javax.swing.JButton Im24;
    private javax.swing.JButton Im25;
    private javax.swing.JButton Im26;
    private javax.swing.JButton Im27;
    private javax.swing.JButton Im28;
    private javax.swing.JButton Im29;
    private javax.swing.JButton Im3;
    private javax.swing.JButton Im30;
    private javax.swing.JButton Im31;
    private javax.swing.JButton Im32;
    private javax.swing.JButton Im4;
    private javax.swing.JButton Im5;
    private javax.swing.JButton Im6;
    private javax.swing.JButton Im7;
    private javax.swing.JButton Im8;
    private javax.swing.JButton Im9;
    private javax.swing.JTextField Samples;
    private javax.swing.JTextField ch1;
    private javax.swing.JTextField ch2;
    private javax.swing.JTextField id1;
    private javax.swing.JTextField id10;
    private javax.swing.JTextField id11;
    private javax.swing.JTextField id12;
    private javax.swing.JTextField id13;
    private javax.swing.JTextField id14;
    private javax.swing.JTextField id15;
    private javax.swing.JTextField id16;
    private javax.swing.JTextField id17;
    private javax.swing.JTextField id18;
    private javax.swing.JTextField id19;
    private javax.swing.JTextField id2;
    private javax.swing.JTextField id20;
    private javax.swing.JTextField id21;
    private javax.swing.JTextField id22;
    private javax.swing.JTextField id23;
    private javax.swing.JTextField id24;
    private javax.swing.JTextField id25;
    private javax.swing.JTextField id26;
    private javax.swing.JTextField id27;
    private javax.swing.JTextField id28;
    private javax.swing.JTextField id29;
    private javax.swing.JTextField id3;
    private javax.swing.JTextField id30;
    private javax.swing.JTextField id31;
    private javax.swing.JTextField id32;
    private javax.swing.JTextField id4;
    private javax.swing.JTextField id5;
    private javax.swing.JTextField id6;
    private javax.swing.JTextField id7;
    private javax.swing.JTextField id8;
    private javax.swing.JTextField id9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel163;
    private javax.swing.JLabel jLabel164;
    private javax.swing.JLabel jLabel165;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel167;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel169;
    private javax.swing.JLabel jLabel170;
    private javax.swing.JLabel jLabel171;
    private javax.swing.JLabel jLabel172;
    private javax.swing.JLabel jLabel173;
    private javax.swing.JLabel jLabel174;
    private javax.swing.JLabel jLabel175;
    private javax.swing.JLabel jLabel176;
    private javax.swing.JLabel jLabel177;
    private javax.swing.JLabel jLabel178;
    private javax.swing.JLabel jLabel179;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel213;
    private javax.swing.JLabel jLabel215;
    private javax.swing.JLabel jLabel216;
    private javax.swing.JLabel jLabel217;
    private javax.swing.JLabel jLabel219;
    private javax.swing.JLabel jLabel220;
    private javax.swing.JLabel jLabel221;
    private javax.swing.JLabel jLabel222;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField multicast;
    private javax.swing.JTextField puerto;
    private javax.swing.JTextField serv;
    // End of variables declaration//GEN-END:variables
}
