/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Datos.Configuracion;
import Datos.Logs;
import Datos.XmlRead;
import Negocio.Coordinador;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author leone
 */
public class Settings extends javax.swing.JPanel {

    /**
     * Creates new form Settings
     */
    private Coordinador cor;
    private Configuracion Conf;
    private Configuracion Confread;
    private ArrayList<String> puertos;
    private ArrayList<String> Images;
    private ArrayList<String> Alias;
    private String PuertoUDP;
    private XmlRead X;
    private Panel P;
    private PanelMixer Mixer;
    private String Inteface;
    public Settings(Coordinador cor,Panel P,PanelMixer Mixer) {
        puertos=new ArrayList<>();
        Images=new ArrayList<>();
        Alias=new ArrayList<>();
        this.cor=cor;
        Conf=new Configuracion();
        Confread=new Configuracion();
        initComponents();
        
        PaintSettings(cor.GetConfiguracion());     
        this.P=P;
        this.Mixer=Mixer;
        X=new XmlRead();
        for(int i=0;i<32;i++){
            Images.add("0");
        }
        Confread=X.Read("config.xml");
        
        Images=Confread.GetListaImages();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel158 = new javax.swing.JLabel();
        id11 = new javax.swing.JTextField();
        jLabel160 = new javax.swing.JLabel();
        id12 = new javax.swing.JTextField();
        jLabel162 = new javax.swing.JLabel();
        id14 = new javax.swing.JTextField();
        jLabel166 = new javax.swing.JLabel();
        jLabel168 = new javax.swing.JLabel();
        jLabel170 = new javax.swing.JLabel();
        jLabel174 = new javax.swing.JLabel();
        jLabel176 = new javax.swing.JLabel();
        jLabel178 = new javax.swing.JLabel();
        id3 = new javax.swing.JTextField();
        id4 = new javax.swing.JTextField();
        id6 = new javax.swing.JTextField();
        id19 = new javax.swing.JTextField();
        id20 = new javax.swing.JTextField();
        id22 = new javax.swing.JTextField();
        id27 = new javax.swing.JTextField();
        id28 = new javax.swing.JTextField();
        id30 = new javax.swing.JTextField();
        Im3 = new javax.swing.JButton();
        Im4 = new javax.swing.JButton();
        Im6 = new javax.swing.JButton();
        Im11 = new javax.swing.JButton();
        Im12 = new javax.swing.JButton();
        Im14 = new javax.swing.JButton();
        Im19 = new javax.swing.JButton();
        Im20 = new javax.swing.JButton();
        Im22 = new javax.swing.JButton();
        Im27 = new javax.swing.JButton();
        Im28 = new javax.swing.JButton();
        Im30 = new javax.swing.JButton();
        Im29 = new javax.swing.JButton();
        id29 = new javax.swing.JTextField();
        Im26 = new javax.swing.JButton();
        id26 = new javax.swing.JTextField();
        Im25 = new javax.swing.JButton();
        id25 = new javax.swing.JTextField();
        jLabel172 = new javax.swing.JLabel();
        Im21 = new javax.swing.JButton();
        id21 = new javax.swing.JTextField();
        jLabel167 = new javax.swing.JLabel();
        Im18 = new javax.swing.JButton();
        id18 = new javax.swing.JTextField();
        jLabel165 = new javax.swing.JLabel();
        Im17 = new javax.swing.JButton();
        id17 = new javax.swing.JTextField();
        jLabel164 = new javax.swing.JLabel();
        Im13 = new javax.swing.JButton();
        jLabel159 = new javax.swing.JLabel();
        id13 = new javax.swing.JTextField();
        Im10 = new javax.swing.JButton();
        id10 = new javax.swing.JTextField();
        jLabel157 = new javax.swing.JLabel();
        Im9 = new javax.swing.JButton();
        id9 = new javax.swing.JTextField();
        jLabel156 = new javax.swing.JLabel();
        Im5 = new javax.swing.JButton();
        id5 = new javax.swing.JTextField();
        jLabel216 = new javax.swing.JLabel();
        Im2 = new javax.swing.JButton();
        id2 = new javax.swing.JTextField();
        jLabel222 = new javax.swing.JLabel();
        Im1 = new javax.swing.JButton();
        id1 = new javax.swing.JTextField();
        jLabel217 = new javax.swing.JLabel();
        Default = new javax.swing.JButton();
        Aceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        serv = new javax.swing.JTextField();
        ch1 = new javax.swing.JTextField();
        ch2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        multicast = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        puerto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Frecuencys = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Samples = new javax.swing.JTextField();
        jLabel180 = new javax.swing.JLabel();
        jLabel181 = new javax.swing.JLabel();
        jLabel182 = new javax.swing.JLabel();
        jLabel183 = new javax.swing.JLabel();
        jLabel184 = new javax.swing.JLabel();
        id7 = new javax.swing.JTextField();
        id8 = new javax.swing.JTextField();
        id15 = new javax.swing.JTextField();
        id16 = new javax.swing.JTextField();
        id23 = new javax.swing.JTextField();
        id24 = new javax.swing.JTextField();
        id31 = new javax.swing.JTextField();
        id32 = new javax.swing.JTextField();
        jLabel218 = new javax.swing.JLabel();
        jLabel219 = new javax.swing.JLabel();
        jLabel220 = new javax.swing.JLabel();
        jLabel221 = new javax.swing.JLabel();
        jLabel223 = new javax.swing.JLabel();
        jLabel224 = new javax.swing.JLabel();
        jLabel225 = new javax.swing.JLabel();
        jLabel226 = new javax.swing.JLabel();
        Im7 = new javax.swing.JButton();
        Im8 = new javax.swing.JButton();
        Im15 = new javax.swing.JButton();
        Im16 = new javax.swing.JButton();
        Im23 = new javax.swing.JButton();
        Im24 = new javax.swing.JButton();
        Im31 = new javax.swing.JButton();
        Im32 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        jLabel158.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel158.setForeground(new java.awt.Color(255, 255, 255));
        jLabel158.setText("CHANNEL 6");

        id11.setText("10001");

        jLabel160.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel160.setForeground(new java.awt.Color(255, 255, 255));
        jLabel160.setText("CHANNEL 14");

        id12.setText("10001");

        jLabel162.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel162.setForeground(new java.awt.Color(255, 255, 255));
        jLabel162.setText("CHANNEL 22");

        id14.setText("10001");

        jLabel166.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel166.setForeground(new java.awt.Color(255, 255, 255));
        jLabel166.setText("CHANNEL 7");

        jLabel168.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel168.setForeground(new java.awt.Color(255, 255, 255));
        jLabel168.setText("CHANNEL 15");

        jLabel170.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel170.setForeground(new java.awt.Color(255, 255, 255));
        jLabel170.setText("CHANNEL 23");

        jLabel174.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel174.setForeground(new java.awt.Color(255, 255, 255));
        jLabel174.setText("CHANNEL 8");

        jLabel176.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel176.setForeground(new java.awt.Color(255, 255, 255));
        jLabel176.setText("CHANNEL 16");

        jLabel178.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel178.setForeground(new java.awt.Color(255, 255, 255));
        jLabel178.setText("CHANNEL 24");

        id3.setText("alguien");

        id4.setText("alguien");

        id6.setText("10001");

        id19.setText("10001");
        id19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id19ActionPerformed(evt);
            }
        });

        id20.setText("10001");
        id20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id20ActionPerformed(evt);
            }
        });

        id22.setText("10001");
        id22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id22ActionPerformed(evt);
            }
        });

        id27.setText("10001");
        id27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id27ActionPerformed(evt);
            }
        });

        id28.setText("10001");
        id28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id28ActionPerformed(evt);
            }
        });

        id30.setText("10001");
        id30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id30ActionPerformed(evt);
            }
        });

        Im3.setText("Chose Image");
        Im3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im3ActionPerformed(evt);
            }
        });

        Im4.setText("Chose Image");
        Im4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im4ActionPerformed(evt);
            }
        });

        Im6.setText("Chose Image");
        Im6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im6ActionPerformed(evt);
            }
        });

        Im11.setText("Chose Image");
        Im11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im11ActionPerformed(evt);
            }
        });

        Im12.setText("Chose Image");
        Im12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im12ActionPerformed(evt);
            }
        });

        Im14.setText("Chose Image");
        Im14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im14ActionPerformed(evt);
            }
        });

        Im19.setText("Chose Image");
        Im19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im19ActionPerformed(evt);
            }
        });

        Im20.setText("Chose Image");
        Im20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im20ActionPerformed(evt);
            }
        });

        Im22.setText("Chose Image");
        Im22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im22ActionPerformed(evt);
            }
        });

        Im27.setText("Chose Image");
        Im27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im27ActionPerformed(evt);
            }
        });

        Im28.setText("Chose Image");
        Im28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im28ActionPerformed(evt);
            }
        });

        Im30.setText("Chose Image");
        Im30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im30ActionPerformed(evt);
            }
        });

        Im29.setText("Chose Image");
        Im29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im29ActionPerformed(evt);
            }
        });

        id29.setText("10001");

        Im26.setText("Chose Image");
        Im26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im26ActionPerformed(evt);
            }
        });

        id26.setText("10001");

        Im25.setText("Chose Image");
        Im25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im25ActionPerformed(evt);
            }
        });

        id25.setText("10001");

        jLabel172.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel172.setForeground(new java.awt.Color(255, 255, 255));
        jLabel172.setText("CHANNEL 4");

        Im21.setText("Chose Image");
        Im21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im21ActionPerformed(evt);
            }
        });

        id21.setText("10001");

        jLabel167.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel167.setForeground(new java.awt.Color(255, 255, 255));
        jLabel167.setText("CHANNEL 19");

        Im18.setText("Chose Image");
        Im18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im18ActionPerformed(evt);
            }
        });

        id18.setText("10001");

        jLabel165.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel165.setForeground(new java.awt.Color(255, 255, 255));
        jLabel165.setText("CHANNEL 11");

        Im17.setText("Chose Image");
        Im17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im17ActionPerformed(evt);
            }
        });

        id17.setText("10001");

        jLabel164.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel164.setForeground(new java.awt.Color(255, 255, 255));
        jLabel164.setText("CHANNEL 3");

        Im13.setText("Chose Image");
        Im13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im13ActionPerformed(evt);
            }
        });

        jLabel159.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel159.setForeground(new java.awt.Color(255, 255, 255));
        jLabel159.setText("CHANNEL 18");

        id13.setText("10001");
        id13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id13ActionPerformed(evt);
            }
        });

        Im10.setText("Chose Image");
        Im10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im10ActionPerformed(evt);
            }
        });

        id10.setText("10001");
        id10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id10ActionPerformed(evt);
            }
        });

        jLabel157.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel157.setForeground(new java.awt.Color(255, 255, 255));
        jLabel157.setText("CHANNEL 10");

        Im9.setText("Chose Image");
        Im9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im9ActionPerformed(evt);
            }
        });

        id9.setText("10001");
        id9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id9ActionPerformed(evt);
            }
        });

        jLabel156.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel156.setForeground(new java.awt.Color(255, 255, 255));
        jLabel156.setText("CHANNEL 2");

        Im5.setText("Chose Image");
        Im5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im5ActionPerformed(evt);
            }
        });

        id5.setText("alguien");

        jLabel216.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel216.setForeground(new java.awt.Color(255, 255, 255));
        jLabel216.setText("CHANNEL 17");

        Im2.setText("Chose Image");
        Im2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im2ActionPerformed(evt);
            }
        });

        id2.setText("alguien");

        jLabel222.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel222.setForeground(new java.awt.Color(255, 255, 255));
        jLabel222.setText("CHANNEL 9");

        Im1.setText("Chose Image");
        Im1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im1ActionPerformed(evt);
            }
        });

        id1.setText("alguien");

        jLabel217.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel217.setForeground(new java.awt.Color(255, 255, 255));
        jLabel217.setText("CHANNEL 1");

        Default.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Default.setText("Default");
        Default.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefaultActionPerformed(evt);
            }
        });

        Aceptar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Aceptar.setText("Accept");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SERVIDOR");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PUERTO UDP");

        serv.setText("127.0.0.1");
        serv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servActionPerformed(evt);
            }
        });

        ch1.setText("10001");
        ch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch1ActionPerformed(evt);
            }
        });

        ch2.setText("10001");
        ch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MULTICAST");

        multicast.setText("230.0.0.1");
        multicast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multicastActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PUERTO TCP");

        puerto.setText("10000");
        puerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puertoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FRECUENCIA");

        Frecuencys.setText("48000");
        Frecuencys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrecuencysActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MUESTRA");

        Samples.setText("128");
        Samples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SamplesActionPerformed(evt);
            }
        });

        jLabel180.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel180.setForeground(new java.awt.Color(255, 255, 255));
        jLabel180.setText("CHANNEL 20");

        jLabel181.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel181.setForeground(new java.awt.Color(255, 255, 255));
        jLabel181.setText("CHANNEL 12");

        jLabel182.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel182.setForeground(new java.awt.Color(255, 255, 255));
        jLabel182.setText("CHANNEL 5");

        jLabel183.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel183.setForeground(new java.awt.Color(255, 255, 255));
        jLabel183.setText("CHANNEL 13");

        jLabel184.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel184.setForeground(new java.awt.Color(255, 255, 255));
        jLabel184.setText("CHANNEL 21");

        id7.setText("alguien");

        id8.setText("alguien");
        id8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id8ActionPerformed(evt);
            }
        });

        id15.setText("alguien");

        id16.setText("alguien");

        id23.setText("alguien");

        id24.setText("alguien");

        id31.setText("alguien");

        id32.setText("alguien");

        jLabel218.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel218.setForeground(new java.awt.Color(255, 255, 255));
        jLabel218.setText("CHANNEL 25");

        jLabel219.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel219.setForeground(new java.awt.Color(255, 255, 255));
        jLabel219.setText("CHANNEL 26");

        jLabel220.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel220.setForeground(new java.awt.Color(255, 255, 255));
        jLabel220.setText("CHANNEL 27");

        jLabel221.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel221.setForeground(new java.awt.Color(255, 255, 255));
        jLabel221.setText("CHANNEL 28");

        jLabel223.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel223.setForeground(new java.awt.Color(255, 255, 255));
        jLabel223.setText("CHANNEL 29");

        jLabel224.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel224.setForeground(new java.awt.Color(255, 255, 255));
        jLabel224.setText("CHANNEL 30");

        jLabel225.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel225.setForeground(new java.awt.Color(255, 255, 255));
        jLabel225.setText("CHANNEL 31");

        jLabel226.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel226.setForeground(new java.awt.Color(255, 255, 255));
        jLabel226.setText("CHANNEL 32");

        Im7.setText("Chose Image");
        Im7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im7ActionPerformed(evt);
            }
        });

        Im8.setText("Chose Image");
        Im8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im8ActionPerformed(evt);
            }
        });

        Im15.setText("Chose Image");
        Im15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im15ActionPerformed(evt);
            }
        });

        Im16.setText("Chose Image");
        Im16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im16ActionPerformed(evt);
            }
        });

        Im23.setText("Chose Image");
        Im23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im23ActionPerformed(evt);
            }
        });

        Im24.setText("Chose Image");
        Im24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im24ActionPerformed(evt);
            }
        });

        Im31.setText("Chose Image");
        Im31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im31ActionPerformed(evt);
            }
        });

        Im32.setText("Chose Image");
        Im32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Im32ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel217)
                                        .addGap(11, 11, 11)
                                        .addComponent(id1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50))
                                    .addComponent(Im1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel156)
                                        .addGap(11, 11, 11)
                                        .addComponent(id9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52))
                                    .addComponent(Im9, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel164)
                                        .addGap(4, 4, 4)
                                        .addComponent(id17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50))
                                    .addComponent(Im17, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel172)
                                        .addGap(4, 4, 4)
                                        .addComponent(id25, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Im25, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel182)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(id3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(Im3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel158)
                                        .addGap(4, 4, 4)
                                        .addComponent(id11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(Im11, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(54, 54, 54)
                                .addComponent(jLabel166)
                                .addGap(4, 4, 4)
                                .addComponent(id19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)
                                .addComponent(jLabel174)
                                .addGap(18, 18, 18)
                                .addComponent(id27, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(serv, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(multicast, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(puerto, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(Frecuencys, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(Samples, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(50, 50, 50)
                                .addComponent(ch1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(ch2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(105, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Im19, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel222)
                                                .addGap(11, 11, 11)
                                                .addComponent(id2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(50, 50, 50))
                                            .addComponent(Im2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(60, 60, 60)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel157)
                                                .addGap(4, 4, 4)
                                                .addComponent(id10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(52, 52, 52))
                                            .addComponent(Im10, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(jLabel165)
                                                .addGap(4, 4, 4)
                                                .addComponent(id18, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(78, 78, 78)
                                                .addComponent(jLabel181)
                                                .addGap(6, 6, 6)
                                                .addComponent(id26, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(73, 73, 73)
                                                .addComponent(jLabel183)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(id4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(74, 74, 74))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addComponent(Im18, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(41, 41, 41)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel160)
                                                .addGap(4, 4, 4)
                                                .addComponent(id12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(80, 80, 80))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(Im12, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(60, 60, 60)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel168)
                                                .addGap(4, 4, 4)
                                                .addComponent(id20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(50, 50, 50))
                                            .addComponent(Im20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(39, 39, 39)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel178)
                                        .addGap(18, 18, 18)
                                        .addComponent(id30, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Im28, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Im27, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(31, 31, 31))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel176)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(id28, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(56, 56, 56)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel216)
                                                .addGap(11, 11, 11)
                                                .addComponent(id5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(50, 50, 50))
                                            .addComponent(Im5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Im7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(60, 60, 60)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel159)
                                                .addGap(4, 4, 4)
                                                .addComponent(id13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(52, 52, 52))
                                            .addComponent(Im13, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Im8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(Im26, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel167)
                                                        .addGap(4, 4, 4)
                                                        .addComponent(id21, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(80, 80, 80)
                                                        .addComponent(jLabel180)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(id29, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(70, 70, 70)
                                                        .addComponent(jLabel184)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(id6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(86, 86, 86)
                                                        .addComponent(Im4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(35, 35, 35))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addComponent(Im15, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(Im21, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel220)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(id15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(Default, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                            .addComponent(Im16, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                            .addComponent(Im23, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                            .addComponent(Im29, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addGap(79, 79, 79)
                                                                            .addComponent(Im6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGap(67, 67, 67)
                                                                .addComponent(jLabel221)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(id16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(81, 81, 81)
                                                                .addComponent(jLabel223)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(id23, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE))))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel218)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(id7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(108, 108, 108)
                                        .addComponent(jLabel219)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(id8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel224)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(id24, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel225)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(id31, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel226)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(id32, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Im24, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel162)
                                                    .addGap(4, 4, 4)
                                                    .addComponent(id14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(26, 26, 26)
                                                    .addComponent(Im14, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(55, 55, 55)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel170)
                                                .addGap(4, 4, 4)
                                                .addComponent(id22, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(50, 50, 50))
                                            .addComponent(Im22, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Im31, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(79, 79, 79)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Im30, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Im32, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 67, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(serv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(multicast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Frecuencys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Samples, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(ch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel217)
                    .addComponent(id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel156)
                    .addComponent(id9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel164)
                    .addComponent(id17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel172)
                    .addComponent(id25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(id3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel182))
                    .addComponent(jLabel158)
                    .addComponent(id11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel166)
                    .addComponent(id19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(id27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel174)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Im1)
                    .addComponent(Im17)
                    .addComponent(Im9)
                    .addComponent(Im25)
                    .addComponent(Im3)
                    .addComponent(Im11)
                    .addComponent(Im19)
                    .addComponent(Im27))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel222)
                    .addComponent(id2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel157)
                    .addComponent(id10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel165)
                    .addComponent(id18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(id26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel181))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(id4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel183))
                    .addComponent(jLabel160)
                    .addComponent(id12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel168)
                    .addComponent(id20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel176)
                        .addComponent(id28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Im10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Im18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Im4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Im26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Im12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Im20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Im28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Im2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel216)
                    .addComponent(id5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel159)
                    .addComponent(id13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel167)
                    .addComponent(id21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(id29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel180))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(id6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel184))
                    .addComponent(jLabel162)
                    .addComponent(id14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel170)
                    .addComponent(id22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(id30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel178)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Im13)
                    .addComponent(Im5)
                    .addComponent(Im29)
                    .addComponent(Im6)
                    .addComponent(Im14)
                    .addComponent(Im22)
                    .addComponent(Im21)
                    .addComponent(Im30))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel218)
                    .addComponent(jLabel219)
                    .addComponent(jLabel220)
                    .addComponent(jLabel221)
                    .addComponent(jLabel223)
                    .addComponent(jLabel224)
                    .addComponent(jLabel225)
                    .addComponent(jLabel226))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Im7)
                    .addComponent(Im8)
                    .addComponent(Im15)
                    .addComponent(Im16)
                    .addComponent(Im23)
                    .addComponent(Im24)
                    .addComponent(Im31)
                    .addComponent(Im32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Default, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void id19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id19ActionPerformed

    private void id20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id20ActionPerformed

    private void id22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id22ActionPerformed

    private void id27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id27ActionPerformed

    private void id28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id28ActionPerformed

    private void id30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id30ActionPerformed

    private void Im3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im3ActionPerformed
        // TODO add your handling code here:
        SaveImage(2);
    }//GEN-LAST:event_Im3ActionPerformed

    private void Im4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im4ActionPerformed
        // TODO add your handling code here:
        SaveImage(3);
    }//GEN-LAST:event_Im4ActionPerformed

    private void Im6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im6ActionPerformed
        // TODO add your handling code here:
        SaveImage(5);
    }//GEN-LAST:event_Im6ActionPerformed

    private void Im11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im11ActionPerformed
        // TODO add your handling code here:
        SaveImage(10);
    }//GEN-LAST:event_Im11ActionPerformed

    private void Im12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im12ActionPerformed
        // TODO add your handling code here:
        SaveImage(11);
    }//GEN-LAST:event_Im12ActionPerformed

    private void Im14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im14ActionPerformed
        // TODO add your handling code here:
        SaveImage(13);
    }//GEN-LAST:event_Im14ActionPerformed

    private void Im19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im19ActionPerformed
        // TODO add your handling code here:
        SaveImage(18);
    }//GEN-LAST:event_Im19ActionPerformed

    private void Im20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im20ActionPerformed
        // TODO add your handling code here:
        SaveImage(19);
    }//GEN-LAST:event_Im20ActionPerformed

    private void Im22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im22ActionPerformed
        // TODO add your handling code here:
        SaveImage(21);
    }//GEN-LAST:event_Im22ActionPerformed

    private void Im27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im27ActionPerformed
        // TODO add your handling code here:
        SaveImage(26);
    }//GEN-LAST:event_Im27ActionPerformed

    private void Im28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im28ActionPerformed
        // TODO add your handling code here:
        SaveImage(27);
    }//GEN-LAST:event_Im28ActionPerformed

    private void Im30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im30ActionPerformed
        // TODO add your handling code here:
        SaveImage(29);
    }//GEN-LAST:event_Im30ActionPerformed

    private void Im29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im29ActionPerformed
        // TODO add your handling code here:
        SaveImage(28);
    }//GEN-LAST:event_Im29ActionPerformed

    private void Im26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im26ActionPerformed
        // TODO add your handling code here:
        SaveImage(25);
    }//GEN-LAST:event_Im26ActionPerformed

    private void Im25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im25ActionPerformed
        // TODO add your handling code here:
        SaveImage(24);
    }//GEN-LAST:event_Im25ActionPerformed

    private void Im21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im21ActionPerformed
        // TODO add your handling code here:
        SaveImage(20);
    }//GEN-LAST:event_Im21ActionPerformed

    private void Im18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im18ActionPerformed
        // TODO add your handling code here:
        SaveImage(17);
    }//GEN-LAST:event_Im18ActionPerformed

    private void Im17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im17ActionPerformed
        // TODO add your handling code here:
        SaveImage(16);
    }//GEN-LAST:event_Im17ActionPerformed

    private void Im13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im13ActionPerformed
        // TODO add your handling code here:
        SaveImage(12);
    }//GEN-LAST:event_Im13ActionPerformed

    private void id13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id13ActionPerformed

    private void Im10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im10ActionPerformed
        // TODO add your handling code here:
        SaveImage(9);
    }//GEN-LAST:event_Im10ActionPerformed

    private void id10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id10ActionPerformed

    private void Im9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im9ActionPerformed
        // TODO add your handling code here:
        SaveImage(8);
    }//GEN-LAST:event_Im9ActionPerformed

    private void id9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id9ActionPerformed

    private void Im5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im5ActionPerformed
        // TODO add your handling code here:
        SaveImage(4);
    }//GEN-LAST:event_Im5ActionPerformed

    private void Im2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im2ActionPerformed
        // TODO add your handling code here:
        SaveImage(1);
    }//GEN-LAST:event_Im2ActionPerformed

    private void Im1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im1ActionPerformed
        // TODO add your handling code here:
        try{
            final JFileChooser fc=new JFileChooser();
            if(fc.showOpenDialog(null)==JFileChooser.APPROVE_OPTION){
                String path=fc.getSelectedFile().getAbsolutePath();
                String nombre=fc.getSelectedFile().getName();

                File inFile = new File(path);
                File outFile = new File(nombre);
                FileInputStream in = new FileInputStream(inFile);
                FileOutputStream out = new FileOutputStream(outFile);
                int c;
                while( (c = in.read() ) != -1)
                out.write(c);
                in.close();
                out.close();
                Images.remove(0);
                Images.add(0,nombre);

            }
            else
            {
                Images.add(null);
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error de archivo ");
        }
    }//GEN-LAST:event_Im1ActionPerformed

    private void DefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefaultActionPerformed
        // TODO add your handling code here:
        //leer xml default
        //escribir xml

        cor.DefaultXml();
        //pintar todos los modulos a la configuracion default
        X=new XmlRead();
        Conf=X.Read("default.xml");
        this.ch1.setText(Conf.GetPortUDP());
        this.ch2.setText(Conf.GetLista().get(1));

        this.id9.setText(Conf.GetLista().get(8));
        this.id10.setText(Conf.GetLista().get(9));
        this.id11.setText(Conf.GetLista().get(10));
        this.id12.setText(Conf.GetLista().get(11));
        this.id13.setText(Conf.GetLista().get(12));
        this.id14.setText(Conf.GetLista().get(13));
        

        this.id1.setText(Conf.GetAlias().get(0));
        this.id2.setText(Conf.GetAlias().get(1));
        this.id3.setText(Conf.GetAlias().get(2));
        this.id4.setText(Conf.GetAlias().get(3));
        this.id5.setText(Conf.GetAlias().get(4));
        this.id6.setText(Conf.GetAlias().get(5));
        this.id7.setText(Conf.GetAlias().get(6));
        this.id8.setText(Conf.GetAlias().get(7));
        this.id9.setText(Conf.GetAlias().get(8));
        this.id10.setText(Conf.GetAlias().get(9));
        this.id11.setText(Conf.GetAlias().get(10));
        this.id12.setText(Conf.GetAlias().get(11));
        this.id13.setText(Conf.GetAlias().get(12));
        this.id14.setText(Conf.GetAlias().get(13));
        this.id15.setText(Conf.GetAlias().get(14));
        this.id16.setText(Conf.GetAlias().get(15));
        this.id17.setText(Conf.GetAlias().get(16));
        this.id18.setText(Conf.GetAlias().get(17));
        this.id19.setText(Conf.GetAlias().get(18));
        this.id20.setText(Conf.GetAlias().get(19));
        this.id21.setText(Conf.GetAlias().get(20));
        this.id22.setText(Conf.GetAlias().get(21));
        this.id23.setText(Conf.GetAlias().get(22));
        this.id24.setText(Conf.GetAlias().get(23));
        this.id25.setText(Conf.GetAlias().get(24));
        this.id26.setText(Conf.GetAlias().get(25));
        this.id27.setText(Conf.GetAlias().get(26));
        this.id28.setText(Conf.GetAlias().get(27));
        this.id29.setText(Conf.GetAlias().get(28));
        this.id30.setText(Conf.GetAlias().get(29));
        this.id31.setText(Conf.GetAlias().get(30));
        this.id32.setText(Conf.GetAlias().get(31));

        this.serv.setText(Conf.GetServidor());
        this.multicast.setText(Conf.GetMultiCast());
        this.puerto.setText(Conf.GetPuerto());
        Frecuencys.setText(Integer.toHexString(Conf.GetFrecuencia()));

    }//GEN-LAST:event_DefaultActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        if(!puertos.isEmpty()){
            puertos.clear();
        }
        if(!Alias.isEmpty()){
            Alias.clear();
        }

        //Images.clear();
        Conf.SetMultiCast(multicast.getText());
        String a=multicast.getText();
        if(a.equals("") || a.equals(null)){
            JOptionPane.showMessageDialog(null, "No se ha llenado un campo");
            return;
        }

        Conf.SetPuerto(puerto.getText());
        a=puerto.getText();
        if(a.equals("") || a.equals(null)){
            JOptionPane.showMessageDialog(null, "No se ha llenado un campo");
            return;
        }

        Conf.SetServidor(serv.getText());
        a=serv.getText();
        if(a.equals("") || a.equals(null)){
            JOptionPane.showMessageDialog(null, "No se ha llenado un campo");
            return;
        }

        if(Frecuencys.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No se ha llenado un campo");
            return;
        }

        if(Samples.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No se ha llenado un campo");
            return;
        }

        boolean bandera1=false;
        if(Frecuencys.getText().equals("44100") || Frecuencys.getText().equals("48000")){
            bandera1=true;
        }
        bandera1=true;

        boolean bandera2=false;
        if(Samples.getText().equals("128") || Samples.getText().equals("256") || Samples.getText().equals("512") || Samples.getText().equals("64")){
            bandera2=true;
        }

        if(!bandera1){
            JOptionPane.showMessageDialog(null, "la frecuencia de muestreo no es la correcta");
            return;
        }

        if(!bandera2){
            JOptionPane.showMessageDialog(null, "El tamaño de muestra no es el correcto");
            return;
        }

        Conf.SetFrecuencia(Integer.parseInt(Frecuencys.getText()) );

        Conf.SetMuestra(Integer.parseInt(Samples.getText()));

        //crear lista de todos lo canales

        if(ch1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No se ha especificado un puerto");
            return;
        }

        if(ch2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No se ha especificado un puerto");
            return;
        }
        Inteface=P.GetNetwork();

        if(Inteface==null){
            Conf.SetNet("default");
        }
        else{
            Conf.SetNet(Inteface);
        }

        Conf.SetPortUDP(ch1.getText());

        
       

        //crear lista de alias
        Alias.add(id1.getText());
        Alias.add(id2.getText());
        Alias.add(id3.getText());
        Alias.add(id4.getText());
        Alias.add(id5.getText());
        Alias.add(id6.getText());
        Alias.add(id7.getText());
        Alias.add(id8.getText());    
        Alias.add(id9.getText());
        Alias.add(id10.getText());
        Alias.add(id11.getText());
        Alias.add(id12.getText());
        Alias.add(id13.getText());
        Alias.add(id14.getText());
        Alias.add(id15.getText());
        Alias.add(id16.getText());
        Alias.add(id17.getText());
        Alias.add(id18.getText());
        Alias.add(id19.getText());
        Alias.add(id20.getText());
        Alias.add(id21.getText());
        Alias.add(id22.getText());
        Alias.add(id23.getText());
        Alias.add(id24.getText());
        Alias.add(id25.getText());
        Alias.add(id26.getText());
        Alias.add(id27.getText());
        Alias.add(id28.getText());
        Alias.add(id29.getText());
        Alias.add(id30.getText());
        Alias.add(id31.getText());
        Alias.add(id32.getText());

        Conf.SetLista(puertos);
        Conf.SetAlias(Alias);

        //lista de images (directorios)
        Conf.SetListaImages(Images);

        try{
            cor.WriteXml(Conf,"config.xml");
            //cor.WriteXml(Conf,"conf");

            JOptionPane.showMessageDialog(null, "Configuracion guardada exitosamente");
            Mixer.SetAlias(Alias);
            Mixer.SetImages(Images);

        }
        catch(Exception e){
            System.out.println("Error en escritura de archivo de configuracion "+e);
            JOptionPane.showMessageDialog(null, "Error de configuracion");
            Logs.Write("Error en escritura de archivo de configuracion");
        }

    }//GEN-LAST:event_AceptarActionPerformed

    private void servActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_servActionPerformed

    private void ch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch1ActionPerformed

    private void ch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch2ActionPerformed

    private void multicastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multicastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multicastActionPerformed

    private void puertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puertoActionPerformed

    private void FrecuencysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrecuencysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FrecuencysActionPerformed

    private void SamplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SamplesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SamplesActionPerformed

    private void Im7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im7ActionPerformed
        // TODO add your handling code here:
        SaveImage(6);
    }//GEN-LAST:event_Im7ActionPerformed

    private void Im8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im8ActionPerformed
        // TODO add your handling code here:
        SaveImage(7);
    }//GEN-LAST:event_Im8ActionPerformed

    private void Im15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im15ActionPerformed
        // TODO add your handling code here:
        SaveImage(14);
    }//GEN-LAST:event_Im15ActionPerformed

    private void Im16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im16ActionPerformed
        // TODO add your handling code here:
        SaveImage(15);
    }//GEN-LAST:event_Im16ActionPerformed

    private void Im23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im23ActionPerformed
        // TODO add your handling code here:
        SaveImage(22);
    }//GEN-LAST:event_Im23ActionPerformed

    private void Im24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im24ActionPerformed
        // TODO add your handling code here:
        SaveImage(23);
    }//GEN-LAST:event_Im24ActionPerformed

    private void Im31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im31ActionPerformed
        // TODO add your handling code here:
        SaveImage(30);
    }//GEN-LAST:event_Im31ActionPerformed

    private void Im32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Im32ActionPerformed
        // TODO add your handling code here:
        SaveImage(31);
    }//GEN-LAST:event_Im32ActionPerformed

    private void id8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id8ActionPerformed

    private void PaintSettings(Configuracion C){
        
        ArrayList<String> puertos2=C.GetLista();
        ArrayList<String> nombres=C.GetAlias();
        multicast.setText(C.GetMultiCast());
        serv.setText(C.GetServidor());
        puerto.setText(C.GetPuerto());
        Samples.setText(Integer.toString(C.GetMuestra()));
        Frecuencys.setText(Integer.toString(C.GetFrecuencia()));
        ch1.setText(C.GetPortUDP());
        ch2.setText(puertos2.get(1));
        
        id1.setText(nombres.get(0));
        id2.setText(nombres.get(1));
        id3.setText(nombres.get(2));
        id4.setText(nombres.get(3));
        id5.setText(nombres.get(4));
        id6.setText(nombres.get(5));
        id7.setText(nombres.get(6));
        id8.setText(nombres.get(7));
        id9.setText(nombres.get(8));
        id10.setText(nombres.get(9));
        id11.setText(nombres.get(10));
        id12.setText(nombres.get(11));
        id13.setText(nombres.get(12));
        id14.setText(nombres.get(13));
        id15.setText(nombres.get(14));
        id16.setText(nombres.get(15));
        id17.setText(nombres.get(16));
        id18.setText(nombres.get(17));
        id19.setText(nombres.get(18));
        id20.setText(nombres.get(19));
        id21.setText(nombres.get(20));
        id22.setText(nombres.get(21));
        id23.setText(nombres.get(22));
        id24.setText(nombres.get(23));
        id25.setText(nombres.get(24));
        id26.setText(nombres.get(25));
        id27.setText(nombres.get(26));
        id28.setText(nombres.get(27));
        id29.setText(nombres.get(28));
        id30.setText(nombres.get(29));
        id31.setText(nombres.get(30));
        id32.setText(nombres.get(31));
        
        
        
        
    }
    
     private void SaveImage(int index){
        try{
            final JFileChooser fc=new JFileChooser();
            if(fc.showOpenDialog(null)==JFileChooser.APPROVE_OPTION){
               String path=fc.getSelectedFile().getAbsolutePath();
               String nombre=fc.getSelectedFile().getName();
               File inFile = new File(path);
               File outFile = new File(nombre);
               FileInputStream in = new FileInputStream(inFile);
               FileOutputStream out = new FileOutputStream(outFile);
               int c;
                while( (c = in.read() ) != -1)
                    out.write(c);
                in.close();
                out.close();
                Images.remove(index);
                Images.add(index,nombre);
                
            }
            else
            {
               Images.add(null);
            }            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error de archivo ");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Default;
    private javax.swing.JTextField Frecuencys;
    private javax.swing.JButton Im1;
    private javax.swing.JButton Im10;
    private javax.swing.JButton Im11;
    private javax.swing.JButton Im12;
    private javax.swing.JButton Im13;
    private javax.swing.JButton Im14;
    private javax.swing.JButton Im15;
    private javax.swing.JButton Im16;
    private javax.swing.JButton Im17;
    private javax.swing.JButton Im18;
    private javax.swing.JButton Im19;
    private javax.swing.JButton Im2;
    private javax.swing.JButton Im20;
    private javax.swing.JButton Im21;
    private javax.swing.JButton Im22;
    private javax.swing.JButton Im23;
    private javax.swing.JButton Im24;
    private javax.swing.JButton Im25;
    private javax.swing.JButton Im26;
    private javax.swing.JButton Im27;
    private javax.swing.JButton Im28;
    private javax.swing.JButton Im29;
    private javax.swing.JButton Im3;
    private javax.swing.JButton Im30;
    private javax.swing.JButton Im31;
    private javax.swing.JButton Im32;
    private javax.swing.JButton Im4;
    private javax.swing.JButton Im5;
    private javax.swing.JButton Im6;
    private javax.swing.JButton Im7;
    private javax.swing.JButton Im8;
    private javax.swing.JButton Im9;
    private javax.swing.JTextField Samples;
    private javax.swing.JTextField ch1;
    private javax.swing.JTextField ch2;
    private javax.swing.JTextField id1;
    private javax.swing.JTextField id10;
    private javax.swing.JTextField id11;
    private javax.swing.JTextField id12;
    private javax.swing.JTextField id13;
    private javax.swing.JTextField id14;
    private javax.swing.JTextField id15;
    private javax.swing.JTextField id16;
    private javax.swing.JTextField id17;
    private javax.swing.JTextField id18;
    private javax.swing.JTextField id19;
    private javax.swing.JTextField id2;
    private javax.swing.JTextField id20;
    private javax.swing.JTextField id21;
    private javax.swing.JTextField id22;
    private javax.swing.JTextField id23;
    private javax.swing.JTextField id24;
    private javax.swing.JTextField id25;
    private javax.swing.JTextField id26;
    private javax.swing.JTextField id27;
    private javax.swing.JTextField id28;
    private javax.swing.JTextField id29;
    private javax.swing.JTextField id3;
    private javax.swing.JTextField id30;
    private javax.swing.JTextField id31;
    private javax.swing.JTextField id32;
    private javax.swing.JTextField id4;
    private javax.swing.JTextField id5;
    private javax.swing.JTextField id6;
    private javax.swing.JTextField id7;
    private javax.swing.JTextField id8;
    private javax.swing.JTextField id9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel164;
    private javax.swing.JLabel jLabel165;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel167;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel170;
    private javax.swing.JLabel jLabel172;
    private javax.swing.JLabel jLabel174;
    private javax.swing.JLabel jLabel176;
    private javax.swing.JLabel jLabel178;
    private javax.swing.JLabel jLabel180;
    private javax.swing.JLabel jLabel181;
    private javax.swing.JLabel jLabel182;
    private javax.swing.JLabel jLabel183;
    private javax.swing.JLabel jLabel184;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel216;
    private javax.swing.JLabel jLabel217;
    private javax.swing.JLabel jLabel218;
    private javax.swing.JLabel jLabel219;
    private javax.swing.JLabel jLabel220;
    private javax.swing.JLabel jLabel221;
    private javax.swing.JLabel jLabel222;
    private javax.swing.JLabel jLabel223;
    private javax.swing.JLabel jLabel224;
    private javax.swing.JLabel jLabel225;
    private javax.swing.JLabel jLabel226;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField multicast;
    private javax.swing.JTextField puerto;
    private javax.swing.JTextField serv;
    // End of variables declaration//GEN-END:variables
}
